spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crud
    username: root
    password: qwerty12345678910#
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop

server:
  port: 5050
